name = "poke-wiki"
compatibility_date = "2025-07-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[[env.production.routes]]
pattern = "*"
zone_name = ""

[env.production]
name = "poke-wiki"
compatibility_date = "2025-07-22"
